apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-data
data:
  hello.txt: 'Hi'
  bonjour.txt: 'Salut'
  hola.txt: '¿Qué tal?'
  zdravstvuyte.txt: 'Privet'
  salve.txt: 'ciao'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: /var/www/
      volumes:
      - name: nginx-volume
        configMap:
          name: nginx-data
---
# Service accessible via the command:
# minikube service nginx-deployment
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32123
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
